/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ShowStudyResult': EventHandler<never, never>
    'ProcessStudyMaterial': EventHandler<never, { topic: 'study.completed'; data: never }>
    'GenerateStudyMaterial': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'study.submit'; data: never }>
  }
    
}